/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.viewsdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing9thnov_stage.viewsdb.TestTableName;


/**
 * ServiceImpl object for domain model class TestTableName.
 *
 * @see TestTableName
 */
@Service("viewsdb.TestTableNameService")
@Validated
public class TestTableNameServiceImpl implements TestTableNameService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TestTableNameServiceImpl.class);


    @Autowired
    @Qualifier("viewsdb.TestTableNameDao")
    private WMGenericDao<TestTableName, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<TestTableName, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "viewsdbTransactionManager")
    @Override
	public TestTableName create(TestTableName testTableName) {
        LOGGER.debug("Creating a new TestTableName with information: {}", testTableName);
        TestTableName testTableNameCreated = this.wmGenericDao.create(testTableName);
        return testTableNameCreated;
    }

	@Transactional(readOnly = true, value = "viewsdbTransactionManager")
	@Override
	public TestTableName getById(Integer testtablenameId) throws EntityNotFoundException {
        LOGGER.debug("Finding TestTableName by id: {}", testtablenameId);
        TestTableName testTableName = this.wmGenericDao.findById(testtablenameId);
        if (testTableName == null){
            LOGGER.debug("No TestTableName found with id: {}", testtablenameId);
            throw new EntityNotFoundException(String.valueOf(testtablenameId));
        }
        return testTableName;
    }

    @Transactional(readOnly = true, value = "viewsdbTransactionManager")
	@Override
	public TestTableName findById(Integer testtablenameId) {
        LOGGER.debug("Finding TestTableName by id: {}", testtablenameId);
        return this.wmGenericDao.findById(testtablenameId);
    }

    @Transactional(readOnly = true, value = "viewsdbTransactionManager")
    @Override
    public TestTableName getByColumn2(String column2) {
        Map<String, Object> column2Map = new HashMap<>();
        column2Map.put("column2", column2);

        LOGGER.debug("Finding TestTableName by unique keys: {}", column2Map);
        TestTableName testTableName = this.wmGenericDao.findByUniqueKey(column2Map);

        if (testTableName == null){
            LOGGER.debug("No TestTableName found with given unique key values: {}", column2Map);
            throw new EntityNotFoundException(String.valueOf(column2Map));
        }

        return testTableName;
    }

	@Transactional(rollbackFor = EntityNotFoundException.class, value = "viewsdbTransactionManager")
	@Override
	public TestTableName update(TestTableName testTableName) throws EntityNotFoundException {
        LOGGER.debug("Updating TestTableName with information: {}", testTableName);
        this.wmGenericDao.update(testTableName);

        Integer testtablenameId = testTableName.getId();

        return this.wmGenericDao.findById(testtablenameId);
    }

    @Transactional(value = "viewsdbTransactionManager")
	@Override
	public TestTableName delete(Integer testtablenameId) throws EntityNotFoundException {
        LOGGER.debug("Deleting TestTableName with id: {}", testtablenameId);
        TestTableName deleted = this.wmGenericDao.findById(testtablenameId);
        if (deleted == null) {
            LOGGER.debug("No TestTableName found with id: {}", testtablenameId);
            throw new EntityNotFoundException(String.valueOf(testtablenameId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "viewsdbTransactionManager")
	@Override
	public Page<TestTableName> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all TestTableNames");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "viewsdbTransactionManager")
    @Override
    public Page<TestTableName> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all TestTableNames");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "viewsdbTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service viewsdb for table TestTableName to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "viewsdbTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "viewsdbTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

