/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class HqlCustomrepsResponse implements Serializable {


    @ColumnAlias("ID")
    private Integer id;

    @ColumnAlias("NAME")
    private String name;

    @ColumnAlias("CHANNEL_TYPE")
    private Integer channelType;

    @ColumnAlias("PIC_URL")
    private String picUrl;

    @ColumnAlias("USERNAME")
    private String username;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getChannelType() {
        return this.channelType;
    }

    public void setChannelType(Integer channelType) {
        this.channelType = channelType;
    }

    public String getPicUrl() {
        return this.picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof HqlCustomrepsResponse)) return false;
        final HqlCustomrepsResponse hqlCustomrepsResponse = (HqlCustomrepsResponse) o;
        return Objects.equals(getId(), hqlCustomrepsResponse.getId()) &&
                Objects.equals(getName(), hqlCustomrepsResponse.getName()) &&
                Objects.equals(getChannelType(), hqlCustomrepsResponse.getChannelType()) &&
                Objects.equals(getPicUrl(), hqlCustomrepsResponse.getPicUrl()) &&
                Objects.equals(getUsername(), hqlCustomrepsResponse.getUsername());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getChannelType(),
                getPicUrl(),
                getUsername());
    }
}
