/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class HqlCustomreps1Response implements Serializable {


    @ColumnAlias("REPS_ID")
    private Integer repsId;

    @ColumnAlias("REPS_NAME")
    private String repsName;

    @ColumnAlias("REPS_CHANNEL_TYPE")
    private Integer repsChannelType;

    @ColumnAlias("REPS_PIC_URL")
    private String repsPicUrl;

    @ColumnAlias("REPS_USERNAME")
    private String repsUsername;

    public Integer getRepsId() {
        return this.repsId;
    }

    public void setRepsId(Integer repsId) {
        this.repsId = repsId;
    }

    public String getRepsName() {
        return this.repsName;
    }

    public void setRepsName(String repsName) {
        this.repsName = repsName;
    }

    public Integer getRepsChannelType() {
        return this.repsChannelType;
    }

    public void setRepsChannelType(Integer repsChannelType) {
        this.repsChannelType = repsChannelType;
    }

    public String getRepsPicUrl() {
        return this.repsPicUrl;
    }

    public void setRepsPicUrl(String repsPicUrl) {
        this.repsPicUrl = repsPicUrl;
    }

    public String getRepsUsername() {
        return this.repsUsername;
    }

    public void setRepsUsername(String repsUsername) {
        this.repsUsername = repsUsername;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof HqlCustomreps1Response)) return false;
        final HqlCustomreps1Response hqlCustomreps1response = (HqlCustomreps1Response) o;
        return Objects.equals(getRepsId(), hqlCustomreps1response.getRepsId()) &&
                Objects.equals(getRepsName(), hqlCustomreps1response.getRepsName()) &&
                Objects.equals(getRepsChannelType(), hqlCustomreps1response.getRepsChannelType()) &&
                Objects.equals(getRepsPicUrl(), hqlCustomreps1response.getRepsPicUrl()) &&
                Objects.equals(getRepsUsername(), hqlCustomreps1response.getRepsUsername());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRepsId(),
                getRepsName(),
                getRepsChannelType(),
                getRepsPicUrl(),
                getRepsUsername());
    }
}
