/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

public class SvCreateTableRequest implements Serializable {



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvCreateTableRequest)) return false;
        final SvCreateTableRequest svCreateTableRequest = (SvCreateTableRequest) o;
        return true;
    }

    @Override
    public int hashCode() {
        return Objects.hash();
    }
}
