/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvCustomrepsResponse implements Serializable {


    @ColumnAlias("REPS_ID")
    private BigInteger repsId;

    @ColumnAlias("REPS_NAME")
    private String repsName;

    @ColumnAlias("REPS_CHANNELTYPE")
    private BigInteger repsChanneltype;

    @ColumnAlias("REPS_PICURL")
    private String repsPicurl;

    @ColumnAlias("REPS_USERNAME")
    private String repsUsername;

    public BigInteger getRepsId() {
        return this.repsId;
    }

    public void setRepsId(BigInteger repsId) {
        this.repsId = repsId;
    }

    public String getRepsName() {
        return this.repsName;
    }

    public void setRepsName(String repsName) {
        this.repsName = repsName;
    }

    public BigInteger getRepsChanneltype() {
        return this.repsChanneltype;
    }

    public void setRepsChanneltype(BigInteger repsChanneltype) {
        this.repsChanneltype = repsChanneltype;
    }

    public String getRepsPicurl() {
        return this.repsPicurl;
    }

    public void setRepsPicurl(String repsPicurl) {
        this.repsPicurl = repsPicurl;
    }

    public String getRepsUsername() {
        return this.repsUsername;
    }

    public void setRepsUsername(String repsUsername) {
        this.repsUsername = repsUsername;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvCustomrepsResponse)) return false;
        final SvCustomrepsResponse svCustomrepsResponse = (SvCustomrepsResponse) o;
        return Objects.equals(getRepsId(), svCustomrepsResponse.getRepsId()) &&
                Objects.equals(getRepsName(), svCustomrepsResponse.getRepsName()) &&
                Objects.equals(getRepsChanneltype(), svCustomrepsResponse.getRepsChanneltype()) &&
                Objects.equals(getRepsPicurl(), svCustomrepsResponse.getRepsPicurl()) &&
                Objects.equals(getRepsUsername(), svCustomrepsResponse.getRepsUsername());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRepsId(),
                getRepsName(),
                getRepsChanneltype(),
                getRepsPicurl(),
                getRepsUsername());
    }
}
