/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvLeadsDataResponse implements Serializable {


    @ColumnAlias("ID")
    private BigInteger id;

    @ColumnAlias("CUSTOMER_ID")
    private BigInteger customerId;

    @ColumnAlias("ENTRY_DATE")
    private Date entryDate;

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public BigInteger getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(BigInteger customerId) {
        this.customerId = customerId;
    }

    public Date getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvLeadsDataResponse)) return false;
        final SvLeadsDataResponse svLeadsDataResponse = (SvLeadsDataResponse) o;
        return Objects.equals(getId(), svLeadsDataResponse.getId()) &&
                Objects.equals(getCustomerId(), svLeadsDataResponse.getCustomerId()) &&
                Objects.equals(getEntryDate(), svLeadsDataResponse.getEntryDate());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getCustomerId(),
                getEntryDate());
    }
}
