/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvRepsOrderByResponse implements Serializable {


    @ColumnAlias("ID")
    private BigInteger id;

    @ColumnAlias("NAME")
    private String name;

    @ColumnAlias("CHANNEL_TYPE")
    private BigInteger channelType;

    @ColumnAlias("STREET")
    private String street;

    @ColumnAlias("CITY")
    private String city;

    @ColumnAlias("STATE")
    private String state;

    @ColumnAlias("ZIP")
    private String zip;

    @ColumnAlias("PICURL")
    private String picurl;

    @ColumnAlias("PASSWORD")
    private String password;

    @ColumnAlias("ROLE")
    private String role;

    @ColumnAlias("USERNAME")
    private String username;

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigInteger getChannelType() {
        return this.channelType;
    }

    public void setChannelType(BigInteger channelType) {
        this.channelType = channelType;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getPicurl() {
        return this.picurl;
    }

    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvRepsOrderByResponse)) return false;
        final SvRepsOrderByResponse svRepsOrderByResponse = (SvRepsOrderByResponse) o;
        return Objects.equals(getId(), svRepsOrderByResponse.getId()) &&
                Objects.equals(getName(), svRepsOrderByResponse.getName()) &&
                Objects.equals(getChannelType(), svRepsOrderByResponse.getChannelType()) &&
                Objects.equals(getStreet(), svRepsOrderByResponse.getStreet()) &&
                Objects.equals(getCity(), svRepsOrderByResponse.getCity()) &&
                Objects.equals(getState(), svRepsOrderByResponse.getState()) &&
                Objects.equals(getZip(), svRepsOrderByResponse.getZip()) &&
                Objects.equals(getPicurl(), svRepsOrderByResponse.getPicurl()) &&
                Objects.equals(getPassword(), svRepsOrderByResponse.getPassword()) &&
                Objects.equals(getRole(), svRepsOrderByResponse.getRole()) &&
                Objects.equals(getUsername(), svRepsOrderByResponse.getUsername());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getChannelType(),
                getStreet(),
                getCity(),
                getState(),
                getZip(),
                getPicurl(),
                getPassword(),
                getRole(),
                getUsername());
    }
}
