/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvSalesDataResponse implements Serializable {


    @ColumnAlias("ID")
    private BigInteger id;

    @ColumnAlias("ENTRY_DATE")
    private Date entryDate;

    @ColumnAlias("QUOTE_ID")
    private BigInteger quoteId;

    @ColumnAlias("PRODUCT_ID")
    private BigInteger productId;

    @ColumnAlias("SALES")
    private BigInteger sales;

    @ColumnAlias("IS_RENEWAL")
    private Boolean isRenewal;

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public Date getEntryDate() {
        return this.entryDate;
    }

    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    public BigInteger getQuoteId() {
        return this.quoteId;
    }

    public void setQuoteId(BigInteger quoteId) {
        this.quoteId = quoteId;
    }

    public BigInteger getProductId() {
        return this.productId;
    }

    public void setProductId(BigInteger productId) {
        this.productId = productId;
    }

    public BigInteger getSales() {
        return this.sales;
    }

    public void setSales(BigInteger sales) {
        this.sales = sales;
    }

    public Boolean getIsRenewal() {
        return this.isRenewal;
    }

    public void setIsRenewal(Boolean isRenewal) {
        this.isRenewal = isRenewal;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvSalesDataResponse)) return false;
        final SvSalesDataResponse svSalesDataResponse = (SvSalesDataResponse) o;
        return Objects.equals(getId(), svSalesDataResponse.getId()) &&
                Objects.equals(getEntryDate(), svSalesDataResponse.getEntryDate()) &&
                Objects.equals(getQuoteId(), svSalesDataResponse.getQuoteId()) &&
                Objects.equals(getProductId(), svSalesDataResponse.getProductId()) &&
                Objects.equals(getSales(), svSalesDataResponse.getSales()) &&
                Objects.equals(getIsRenewal(), svSalesDataResponse.getIsRenewal());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getEntryDate(),
                getQuoteId(),
                getProductId(),
                getSales(),
                getIsRenewal());
    }
}
