/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvTasksDataResponse implements Serializable {


    @ColumnAlias("ID")
    private BigInteger id;

    @ColumnAlias("DESCRIPTION")
    private String description;

    @ColumnAlias("DUEDATE")
    private Date duedate;

    @ColumnAlias("DONE")
    private Boolean done;

    @ColumnAlias("REP_ID")
    private BigInteger repId;

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getDuedate() {
        return this.duedate;
    }

    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    public Boolean getDone() {
        return this.done;
    }

    public void setDone(Boolean done) {
        this.done = done;
    }

    public BigInteger getRepId() {
        return this.repId;
    }

    public void setRepId(BigInteger repId) {
        this.repId = repId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvTasksDataResponse)) return false;
        final SvTasksDataResponse svTasksDataResponse = (SvTasksDataResponse) o;
        return Objects.equals(getId(), svTasksDataResponse.getId()) &&
                Objects.equals(getDescription(), svTasksDataResponse.getDescription()) &&
                Objects.equals(getDuedate(), svTasksDataResponse.getDuedate()) &&
                Objects.equals(getDone(), svTasksDataResponse.getDone()) &&
                Objects.equals(getRepId(), svTasksDataResponse.getRepId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getDescription(),
                getDuedate(),
                getDone(),
                getRepId());
    }
}
