/*Generated by WaveMaker Studio*/
package com.testing9thnov_stage.db123__;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

import com.wavemaker.runtime.data.annotations.WMValueInject;
import com.wavemaker.runtime.data.replacers.Scope;
import com.wavemaker.runtime.data.replacers.providers.VariableType;

/**
 * ShortseqtServerdef generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SHORTSEQT_SERVERDEF`")
public class ShortseqtServerdef implements Serializable {

    private Integer shortid;
    @WMValueInject( type = VariableType.SERVER, name = "USER_NAME", scopes = { Scope.INSERT, Scope.UPDATE })
    private String username;
    @WMValueInject( type = VariableType.SERVER, name = "USER_ID", scopes = { Scope.INSERT, Scope.UPDATE })
    private short id;
    @WMValueInject( type = VariableType.SERVER, name = "DATE", scopes = { Scope.INSERT, Scope.UPDATE })
    private Date curDate;
    @WMValueInject( type = VariableType.SERVER, name = "TIME", scopes = { Scope.INSERT, Scope.UPDATE })
    private Time curTime;
    private String charCol;
    @WMValueInject( type = VariableType.SERVER, name = "DATE", scopes = { Scope.UPDATE })
    private Date currentDateUpdate;
    @WMValueInject( type = VariableType.SERVER, name = "TIME", scopes = { Scope.UPDATE })
    private Time currentTimeUpdate;
    @WMValueInject( type = VariableType.SERVER, name = "DATE", scopes = { Scope.INSERT })
    private Date insertDate;
    @WMValueInject( type = VariableType.SERVER, name = "TIME", scopes = { Scope.INSERT })
    private Time insertTime;
    @WMValueInject( type = VariableType.SERVER, name = "DATE_TIME", scopes = { Scope.INSERT, Scope.UPDATE })
    @Type(type = "DateTime")
    private LocalDateTime datetimeInsertUPdate;
    @WMValueInject( type = VariableType.SERVER, name = "DATE_TIME", scopes = { Scope.INSERT })
    @Type(type = "DateTime")
    private LocalDateTime datetimeInsert;
    @WMValueInject( type = VariableType.SERVER, name = "DATE_TIME", scopes = { Scope.UPDATE })
    @Type(type = "DateTime")
    private LocalDateTime datetimeUpdate;
    @WMValueInject( type = VariableType.SERVER, name = "USER_NAME", scopes = { Scope.INSERT })
    private String usernameInsertable;
    @WMValueInject( type = VariableType.SERVER, name = "USER_ID", scopes = { Scope.INSERT })
    private String useridInsertable;

    @Id
    @SequenceGenerator(name = "generator", sequenceName = "`ShortCountBy5`" , schema = "dbo", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "generator")
    @Column(name = "`SHORTID`", nullable = false, scale = 0, precision = 10)
    public Integer getShortid() {
        return this.shortid;
    }

    public void setShortid(Integer shortid) {
        this.shortid = shortid;
    }

    @Column(name = "`USERNAME`", nullable = false, length = 255)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "`ID`", nullable = false, scale = 0, precision = 5)
    public short getId() {
        return this.id;
    }

    public void setId(short id) {
        this.id = id;
    }

    @Column(name = "`CUR DATE`", nullable = false)
    public Date getCurDate() {
        return this.curDate;
    }

    public void setCurDate(Date curDate) {
        this.curDate = curDate;
    }

    @Column(name = "`CUR TIME`", nullable = false)
    public Time getCurTime() {
        return this.curTime;
    }

    public void setCurTime(Time curTime) {
        this.curTime = curTime;
    }

    @Column(name = "`CHAR COL`", nullable = true, length = 1)
    public String getCharCol() {
        return this.charCol;
    }

    public void setCharCol(String charCol) {
        this.charCol = charCol;
    }

    @Column(name = "`CURRENT DATE UPDATE`", nullable = true, insertable = false)
    public Date getCurrentDateUpdate() {
        return this.currentDateUpdate;
    }

    public void setCurrentDateUpdate(Date currentDateUpdate) {
        this.currentDateUpdate = currentDateUpdate;
    }

    @Column(name = "`CURRENT TIME UPDATE`", nullable = true, insertable = false)
    public Time getCurrentTimeUpdate() {
        return this.currentTimeUpdate;
    }

    public void setCurrentTimeUpdate(Time currentTimeUpdate) {
        this.currentTimeUpdate = currentTimeUpdate;
    }

    @Column(name = "`INSERT DATE`", nullable = true, updatable = false)
    public Date getInsertDate() {
        return this.insertDate;
    }

    public void setInsertDate(Date insertDate) {
        this.insertDate = insertDate;
    }

    @Column(name = "`INSERT TIME`", nullable = true, updatable = false)
    public Time getInsertTime() {
        return this.insertTime;
    }

    public void setInsertTime(Time insertTime) {
        this.insertTime = insertTime;
    }

    @Column(name = "`DATETIME_INSERT_uPDATE`", nullable = true)
    public LocalDateTime getDatetimeInsertUPdate() {
        return this.datetimeInsertUPdate;
    }

    public void setDatetimeInsertUPdate(LocalDateTime datetimeInsertUPdate) {
        this.datetimeInsertUPdate = datetimeInsertUPdate;
    }

    @Column(name = "`DATETIME_INSERT`", nullable = true, updatable = false)
    public LocalDateTime getDatetimeInsert() {
        return this.datetimeInsert;
    }

    public void setDatetimeInsert(LocalDateTime datetimeInsert) {
        this.datetimeInsert = datetimeInsert;
    }

    @Column(name = "`DATETIME_UPDATE`", nullable = true, insertable = false)
    public LocalDateTime getDatetimeUpdate() {
        return this.datetimeUpdate;
    }

    public void setDatetimeUpdate(LocalDateTime datetimeUpdate) {
        this.datetimeUpdate = datetimeUpdate;
    }

    @Column(name = "`USERNAME_INSERTABLE`", nullable = true, updatable = false, length = 255)
    public String getUsernameInsertable() {
        return this.usernameInsertable;
    }

    public void setUsernameInsertable(String usernameInsertable) {
        this.usernameInsertable = usernameInsertable;
    }

    @Column(name = "`USERID_INSERTABLE`", nullable = true, updatable = false, length = 255)
    public String getUseridInsertable() {
        return this.useridInsertable;
    }

    public void setUseridInsertable(String useridInsertable) {
        this.useridInsertable = useridInsertable;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ShortseqtServerdef)) return false;
        final ShortseqtServerdef shortseqtServerdef = (ShortseqtServerdef) o;
        return Objects.equals(getShortid(), shortseqtServerdef.getShortid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getShortid());
    }
}

