/*Generated by WaveMaker Studio*/

package com.testing9thnov_stage.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

@Service
public class Db123__QueryExecutorServiceImpl implements Db123__QueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Db123__QueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("db123__WMQueryExecutor")
    private WMQueryExecutor queryExecutor;


}


