/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing9thnov_stage.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing9thnov_stage.salesdb.Reps;
import com.testing9thnov_stage.salesdb.models.query.*;

public interface SalesdbQueryExecutorService {

    Page<SvRepsOrderByResponse> executeSV_RepsOrderBy(Pageable pageable);

    Downloadable exportSV_RepsOrderBy(ExportType exportType, Pageable pageable);

    Page<HqlCustomreps1Response> executeHQL_CUSTOMREPS1(Pageable pageable);

    Downloadable exportHQL_CUSTOMREPS1(ExportType exportType, Pageable pageable);

    Page<SvCustomrepsResponse> executeSV_CUSTOMREPS(Pageable pageable);

    Downloadable exportSV_CUSTOMREPS(ExportType exportType, Pageable pageable);

    Page<Reps> executeHQL_INOperator(List<Integer> channelType, Pageable pageable);

    Downloadable exportHQL_INOperator(ExportType exportType, List<Integer> channelType, Pageable pageable);

}


