/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing9thnov_stage.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testing9thnov_stage.salesdb.Reps;
import com.testing9thnov_stage.salesdb.models.query.*;

public interface SalesdbQueryExecutorService {

    Page<SvRepsOrderByResponse> executeSV_RepsOrderBy(Pageable pageable);

    Downloadable exportSV_RepsOrderBy(ExportType exportType, Pageable pageable);

    Page<SvStatesDataResponse> executeSV_StatesData(Pageable pageable);

    Downloadable exportSV_StatesData(ExportType exportType, Pageable pageable);

    Page<Reps> executeHQL_INOperator(List<Integer> channelType, Pageable pageable);

    Downloadable exportHQL_INOperator(ExportType exportType, List<Integer> channelType, Pageable pageable);

    Integer executeSV_CreateTable(SvCreateTableRequest svCreateTableRequest);

    Page<SvSalesDataResponse> executeSV_SalesData(Pageable pageable);

    Downloadable exportSV_SalesData(ExportType exportType, Pageable pageable);

    Page<SvProductsDataResponse> executeSV_ProductsData(Pageable pageable);

    Downloadable exportSV_ProductsData(ExportType exportType, Pageable pageable);

    Page<SvChannelsDataResponse> executeSV_ChannelsData(Pageable pageable);

    Downloadable exportSV_ChannelsData(ExportType exportType, Pageable pageable);

    Page<SvFollowUpsDataResponse> executeSV_FollowUpsData(Pageable pageable);

    Downloadable exportSV_FollowUpsData(ExportType exportType, Pageable pageable);

    Page<SvLeadsDataResponse> executeSV_LeadsData(Pageable pageable);

    Downloadable exportSV_LeadsData(ExportType exportType, Pageable pageable);

    Page<SvCustomersDataResponse> executeSV_CustomersData(Pageable pageable);

    Downloadable exportSV_CustomersData(ExportType exportType, Pageable pageable);

    Page<SvTasksDataResponse> executeSV_TasksData(Pageable pageable);

    Downloadable exportSV_TasksData(ExportType exportType, Pageable pageable);

    Page<HqlCustomreps1Response> executeHQL_CUSTOMREPS1(Pageable pageable);

    Downloadable exportHQL_CUSTOMREPS1(ExportType exportType, Pageable pageable);

    Page<SvCustomrepsResponse> executeSV_CUSTOMREPS(Pageable pageable);

    Downloadable exportSV_CUSTOMREPS(ExportType exportType, Pageable pageable);

    Page<SvQuotesDataResponse> executeSv_QuotesData(Pageable pageable);

    Downloadable exportSv_QuotesData(ExportType exportType, Pageable pageable);

}


