/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.salesdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Alltypes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`ALLTYPES`")
public class Alltypes implements Serializable {

    private Integer intid;
    private Byte bytecol;
    private Short shortcol;
    private Long longcol;
    private BigDecimal doublecol;
    private BigInteger bigintcol;
    private BigDecimal bigdeccol;
    private BigDecimal floatcol;
    private String charcol;
    private String stringcol;
    private String textcol;
    private String clobcol;
    private Date datecol;
    private Timestamp datetimecol;
    private Time timecol;
    private Timestamp timestampcol;
    private Boolean booleancol;
    @JsonProperty(access = Access.READ_ONLY)
    private byte[] blobcol;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`INTID`", nullable = false, scale = 0, precision = 10)
    public Integer getIntid() {
        return this.intid;
    }

    public void setIntid(Integer intid) {
        this.intid = intid;
    }

    @Column(name = "`BYTECOL`", nullable = true, scale = 0, precision = 2)
    public Byte getBytecol() {
        return this.bytecol;
    }

    public void setBytecol(Byte bytecol) {
        this.bytecol = bytecol;
    }

    @Column(name = "`SHORTCOL`", nullable = true, scale = 0, precision = 5)
    public Short getShortcol() {
        return this.shortcol;
    }

    public void setShortcol(Short shortcol) {
        this.shortcol = shortcol;
    }

    @Column(name = "`LONGCOL`", nullable = true, scale = 0, precision = 18)
    public Long getLongcol() {
        return this.longcol;
    }

    public void setLongcol(Long longcol) {
        this.longcol = longcol;
    }

    @Column(name = "`DOUBLECOL`", nullable = true, scale = 8, precision = 18)
    public BigDecimal getDoublecol() {
        return this.doublecol;
    }

    public void setDoublecol(BigDecimal doublecol) {
        this.doublecol = doublecol;
    }

    @Column(name = "`BIGINTCOL`", nullable = true, scale = 0, precision = 20)
    public BigInteger getBigintcol() {
        return this.bigintcol;
    }

    public void setBigintcol(BigInteger bigintcol) {
        this.bigintcol = bigintcol;
    }

    @Column(name = "`BIGDECCOL`", nullable = true, scale = 15, precision = 35)
    public BigDecimal getBigdeccol() {
        return this.bigdeccol;
    }

    public void setBigdeccol(BigDecimal bigdeccol) {
        this.bigdeccol = bigdeccol;
    }

    @Column(name = "`FLOATCOL`", nullable = true, scale = 9, precision = 64)
    public BigDecimal getFloatcol() {
        return this.floatcol;
    }

    public void setFloatcol(BigDecimal floatcol) {
        this.floatcol = floatcol;
    }

    @Column(name = "`CHARCOL`", nullable = true, length = 1)
    public String getCharcol() {
        return this.charcol;
    }

    public void setCharcol(String charcol) {
        this.charcol = charcol;
    }

    @Column(name = "`STRINGCOL`", nullable = true, length = 255)
    public String getStringcol() {
        return this.stringcol;
    }

    public void setStringcol(String stringcol) {
        this.stringcol = stringcol;
    }

    @Column(name = "`TEXTCOL`", nullable = true, length = 2147483647)
    public String getTextcol() {
        return this.textcol;
    }

    public void setTextcol(String textcol) {
        this.textcol = textcol;
    }

    @Column(name = "`CLOBCOL`", nullable = true, length = 2147483647)
    public String getClobcol() {
        return this.clobcol;
    }

    public void setClobcol(String clobcol) {
        this.clobcol = clobcol;
    }

    @Column(name = "`DATECOL`", nullable = true)
    public Date getDatecol() {
        return this.datecol;
    }

    public void setDatecol(Date datecol) {
        this.datecol = datecol;
    }

    @Column(name = "`DATETIMECOL`", nullable = true)
    public Timestamp getDatetimecol() {
        return this.datetimecol;
    }

    public void setDatetimecol(Timestamp datetimecol) {
        this.datetimecol = datetimecol;
    }

    @Column(name = "`TIMECOL`", nullable = true)
    public Time getTimecol() {
        return this.timecol;
    }

    public void setTimecol(Time timecol) {
        this.timecol = timecol;
    }

    @Column(name = "`TIMESTAMPCOL`", nullable = true)
    public Timestamp getTimestampcol() {
        return this.timestampcol;
    }

    public void setTimestampcol(Timestamp timestampcol) {
        this.timestampcol = timestampcol;
    }

    @Column(name = "`BOOLEANCOL`", nullable = true)
    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }

    @Column(name = "`BLOBCOL`", nullable = true)
    public byte[] getBlobcol() {
        return this.blobcol;
    }

    public void setBlobcol(byte[] blobcol) {
        this.blobcol = blobcol;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Alltypes)) return false;
        final Alltypes alltypes = (Alltypes) o;
        return Objects.equals(getIntid(), alltypes.getIntid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getIntid());
    }
}

