/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.testing9thnov_stage.viewsdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * AutoIncrementTable generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`AutoIncrement_Table`")
@IdClass(AutoIncrementTableId.class)
public class AutoIncrementTable implements Serializable {

    private Integer id;
    private String name;
    private String _desc;
    private String test;

    @Id
    @Column(name = "`Id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Id
    @Column(name = "`Name`", nullable = false, length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`Desc`", nullable = true, length = 255)
    public String get_desc() {
        return this._desc;
    }

    public void set_desc(String _desc) {
        this._desc = _desc;
    }

    @Column(name = "`Test`", nullable = true, length = 255)
    public String getTest() {
        return this.test;
    }

    public void setTest(String test) {
        this.test = test;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AutoIncrementTable)) return false;
        final AutoIncrementTable autoIncrementTable = (AutoIncrementTable) o;
        return Objects.equals(getId(), autoIncrementTable.getId()) &&
                Objects.equals(getName(), autoIncrementTable.getName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName());
    }
}

