/*Copyright (c) 2017-2018 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testing9thnov_stage.salesdb.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testing9thnov_stage.salesdb.Reps;
import com.testing9thnov_stage.salesdb.service.SalesdbQueryExecutorService;
import com.testing9thnov_stage.salesdb.models.query.*;

@RestController(value = "Salesdb.QueryExecutionController")
@RequestMapping("/salesdb/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private SalesdbQueryExecutorService queryService;

    @RequestMapping(value = "/queries/SV_RepsOrderBy", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "RepsOrderBy")
    public Page<SvRepsOrderByResponse> executeSV_RepsOrderBy(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_RepsOrderBy");
        Page<SvRepsOrderByResponse> _result = queryService.executeSV_RepsOrderBy(pageable);
        LOGGER.debug("got the result for named query: SV_RepsOrderBy, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file for query SV_RepsOrderBy")
    @RequestMapping(value = "/queries/SV_RepsOrderBy/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSV_RepsOrderBy(@PathVariable("exportType") ExportType exportType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: SV_RepsOrderBy");

        return queryService.exportSV_RepsOrderBy(exportType, pageable);
    }

    @RequestMapping(value = "/queries/HQL_CUSTOMREPS1", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "CUSTOM REPS")
    public Page<HqlCustomreps1Response> executeHQL_CUSTOMREPS1(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: HQL_CUSTOMREPS1");
        Page<HqlCustomreps1Response> _result = queryService.executeHQL_CUSTOMREPS1(pageable);
        LOGGER.debug("got the result for named query: HQL_CUSTOMREPS1, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file for query HQL_CUSTOMREPS1")
    @RequestMapping(value = "/queries/HQL_CUSTOMREPS1/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportHQL_CUSTOMREPS1(@PathVariable("exportType") ExportType exportType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: HQL_CUSTOMREPS1");

        return queryService.exportHQL_CUSTOMREPS1(exportType, pageable);
    }

    @RequestMapping(value = "/queries/SV_CUSTOMREPS", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "CUSTOM REPS")
    public Page<SvCustomrepsResponse> executeSV_CUSTOMREPS(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_CUSTOMREPS");
        Page<SvCustomrepsResponse> _result = queryService.executeSV_CUSTOMREPS(pageable);
        LOGGER.debug("got the result for named query: SV_CUSTOMREPS, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file for query SV_CUSTOMREPS")
    @RequestMapping(value = "/queries/SV_CUSTOMREPS/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportSV_CUSTOMREPS(@PathVariable("exportType") ExportType exportType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: SV_CUSTOMREPS");

        return queryService.exportSV_CUSTOMREPS(exportType, pageable);
    }

    @RequestMapping(value = "/queries/HQL_INOperator", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "In Operator")
    public Page<Reps> executeHQL_INOperator(@RequestParam(value = "channelType") List<Integer> channelType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: HQL_INOperator");
        Page<Reps> _result = queryService.executeHQL_INOperator(channelType, pageable);
        LOGGER.debug("got the result for named query: HQL_INOperator, result:{}", _result);
        return _result;
    }

    @ApiOperation(value = "Returns downloadable file for query HQL_INOperator")
    @RequestMapping(value = "/queries/HQL_INOperator/export/{exportType}", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportHQL_INOperator(@PathVariable("exportType") ExportType exportType, @RequestParam(value = "channelType") List<Integer> channelType, Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Exporting named query: HQL_INOperator");

        return queryService.exportHQL_INOperator(exportType, channelType, pageable);
    }

}


